apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app:
spec:
 selector:
   matchLabels:
     app: todoapp
 template:
   metadata:
     labels:
       app: todoapp
   spec:
     containers:
       - name: todoapp
         image: busyboxplus:curl
         resources:
           requests:
             cpu: "100m"
             memory: "100Mi"
           limits:
             cpu: "200m"
             memory: "200Mi"
         ports:
           - containerPort: 80
             hostPort: 30008
